### ISSUE TITLE
Duplicate class Reason compile error if DSC resource SqlServerDsc >=16.0.0 is used in one DSC configuration

### ISSUE THREAD

**Issue by stehlih** [nyanhp/cScom#1]
The upgrade of Sql* Configurations to SqlServerDsc 16.0.0. of CommonTasks are failed because of duplicate symbols (class Reason) with the cScom 1.0.0 resource.

In most Sql* Configuration these behavior can be fixed by importing only the used resource.
But for the SqlPermissions the class Reason is used as resource parameter.

You can reproduce this error with the following code in a DSC configuration using SqlServerDsc 16.0.0:

    Import-DscResource -ModuleName cScom
    Import-DscResource -ModuleName SqlServerDsc -Name SqlPermission

Error output is:

PSDesiredStateConfiguration\node : Der Ressourcenname "Reason" wird bereits von einer anderen Ressource oder
Konfiguration verwendet.
In Zeile:5 Zeichen:5
+     node "localhost_$dscResourceName" {
+     ~~~~
    + CategoryInfo          : InvalidOperation: (:) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordExc
   eption
    + FullyQualifiedErrorId : DuplicateKeywordDefinition,PSDesiredStateConfiguration\node

  [-] 'SqlPermissions' compiles 1.2s (1.2s|0ms)

**Comment by nyanhp** [comment]
Unable to fix this issue. This DSC resource conforms with the required syntax for use with Azure Automanage Machine Configuration and is a standard class-based resource. This is an issue that will increase if people start to develop more class-based resources that should be supported in Azure Automanage as well.
